# Generated by Django 2.2.12 on 2021-03-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='DOB',
        ),
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
